---
title: "linear models"
author: "ASHLEY ROMO"
date: "2023-11-18"
output: github_document
---

```{r, include = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

Load key packages.

```{r}
library(tidyverse)
library(p8105.datasets)
```



## Load and clean the Airbnb data

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |> 
  select(
    price, stars, borough = neighbourhood_group, 
    neighbourhood, room_type) |> 
  filter(borough != "Staten Island")

```


Let's fit a model!!

```{r}
# lm(price ~ stars + borough, date = nyc_airbnb)
fit = 
  nyc_airbnb |> 
  lm(price ~ stars + borough, data = _) #underscore here specifies the dataset
```


Let's look at the `fit`

```{r}
fit # not very helpful

summary(fit) #provides residuals info and coefficient info (estimate, sd error, t value, and p value)

summary(fit)$coef #take out the coefficient table 

coef(fit) # take out value of coefficients alone

# fitted.values(fit) #take out all of the fitted values
```

tidy up the output instead

```{r}
#better way to do this is using glance()

#glance() extracts general model fits statistics aka high level summary of how well the model works, including R^2, adjusted R^2, overal gloval p value, etc

fit |> 
  broom::glance()
```


tidy up the coefficients

```{r}
#use the tidy() function pulls out the coefficient table

#tidy() is a tibble (better than glance because glance outputs a matrix)

fit |> 
  broom::tidy() |> 
  mutate(term = str_replace(term, "^borough", "Borough: ")) |> 
  select(term, estimate, p.value) |> 
  knitr::kable(digits = 3)
```

## Fit another model


```{r}
fit = 
  nyc_airbnb |>
lm(price ~ stars + borough + room_type, data = _)
# when R is creating these indicator variables, it is taking the variable you started out with and assuming there is a factor ordering in alphabetical order
#here bronx is the reference category because it is the first alphabetically, but you can specificy the order


fit = 
  nyc_airbnb |> 
  mutate(
    borough = fct_infreq(borough), #factor based on frequency, so reference category changes. Now, reference is Manhattan
    room_type = fct_infreq(room_type)
  ) |> 
  lm(price ~ stars + borough + room_type, data = _)

fit |> 
  broom::tidy()
```



## Quick look at diagnostics (minute 32)

```{r}
#regression diagnostics boils down to get the residuals and do a careful inspection of residuals to make sure you don't have overly skewed distributions and non-normal distributions
#make sure you have the residuals you meed by using add_residuals(dataframe,added residuals form the model you just fit) function
#output gives us a residual column that shows what happens after you fit this model (here, it is the model = fit) and apply it to this dataset (Data = nyc_airbnb) to compute the residuals that go along with the data

#you can also use this function to check if your model is generalizable  
nyc_airbnb |> 
  modelr::add_residuals(fit) |> 
  ggplot(aes(x = resid)) + #helpful first look
  geom_density() +
  xlim(-100, 500)


nyc_airbnb |> 
  modelr::add_residuals(fit) |> 
  ggplot(aes(x = borough, y = resid)) +  #can plot your residuals
  geom_violin() 

nyc_airbnb |> 
  modelr::add_residuals(fit) |> 
  ggplot(aes(x = stars, y = resid)) + 
  geom_point() 

##always need to check residuals to make sure we are not violating the assumption 
```

Now with a qq plot!

```{r}
nyc_airbnb |> 
  modelr::add_residuals(fit) |> 
  ggplot(aes(sample = resid)) + 
  stat_qq() + 
  stat_qq_line()
```

## Hypothesis test for categorical predictor

fit a "null" and "alternative" model

```{r}
fit |> 
  broom::tidy() #this gives the p values for each variable to see if it is significant

#if you wanted to ask if you need room type (yes vs no), you need to compare a model with the categorical predictor and one without 
fit_null = lm(price ~ stars + borough, data = nyc_airbnb) #linear model of price on stars and borough using nyc_airbnb model
fit_alternative = lm(price ~ stars + borough + room_type, data = nyc_airbnb)
#alternative is the null plus room type  (we want to know if room type is significant)

#can also use the ANOVA 
anova(fit_null, fit_alternative) |> 
  broom::tidy() 
```



